# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_scidi_wrapper', [dirname(__file__)])
        except ImportError:
            import _scidi_wrapper
            return _scidi_wrapper
        if fp is not None:
            try:
                _mod = imp.load_module('_scidi_wrapper', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _scidi_wrapper = swig_import_helper()
    del swig_import_helper
else:
    import _scidi_wrapper
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _scidi_wrapper.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _scidi_wrapper.SwigPyIterator_value(self)
    def incr(self, n=1): return _scidi_wrapper.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _scidi_wrapper.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _scidi_wrapper.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _scidi_wrapper.SwigPyIterator_equal(self, *args)
    def copy(self): return _scidi_wrapper.SwigPyIterator_copy(self)
    def next(self): return _scidi_wrapper.SwigPyIterator_next(self)
    def __next__(self): return _scidi_wrapper.SwigPyIterator___next__(self)
    def previous(self): return _scidi_wrapper.SwigPyIterator_previous(self)
    def advance(self, *args): return _scidi_wrapper.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _scidi_wrapper.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _scidi_wrapper.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _scidi_wrapper.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _scidi_wrapper.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _scidi_wrapper.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _scidi_wrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _scidi_wrapper.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _scidi_wrapper.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _scidi_wrapper.DoubleVector___nonzero__(self)
    def __bool__(self): return _scidi_wrapper.DoubleVector___bool__(self)
    def __len__(self): return _scidi_wrapper.DoubleVector___len__(self)
    def pop(self): return _scidi_wrapper.DoubleVector_pop(self)
    def __getslice__(self, *args): return _scidi_wrapper.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _scidi_wrapper.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _scidi_wrapper.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _scidi_wrapper.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _scidi_wrapper.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _scidi_wrapper.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _scidi_wrapper.DoubleVector_append(self, *args)
    def empty(self): return _scidi_wrapper.DoubleVector_empty(self)
    def size(self): return _scidi_wrapper.DoubleVector_size(self)
    def clear(self): return _scidi_wrapper.DoubleVector_clear(self)
    def swap(self, *args): return _scidi_wrapper.DoubleVector_swap(self, *args)
    def get_allocator(self): return _scidi_wrapper.DoubleVector_get_allocator(self)
    def begin(self): return _scidi_wrapper.DoubleVector_begin(self)
    def end(self): return _scidi_wrapper.DoubleVector_end(self)
    def rbegin(self): return _scidi_wrapper.DoubleVector_rbegin(self)
    def rend(self): return _scidi_wrapper.DoubleVector_rend(self)
    def pop_back(self): return _scidi_wrapper.DoubleVector_pop_back(self)
    def erase(self, *args): return _scidi_wrapper.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _scidi_wrapper.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _scidi_wrapper.DoubleVector_push_back(self, *args)
    def front(self): return _scidi_wrapper.DoubleVector_front(self)
    def back(self): return _scidi_wrapper.DoubleVector_back(self)
    def assign(self, *args): return _scidi_wrapper.DoubleVector_assign(self, *args)
    def resize(self, *args): return _scidi_wrapper.DoubleVector_resize(self, *args)
    def insert(self, *args): return _scidi_wrapper.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _scidi_wrapper.DoubleVector_reserve(self, *args)
    def capacity(self): return _scidi_wrapper.DoubleVector_capacity(self)
    __swig_destroy__ = _scidi_wrapper.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _scidi_wrapper.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _scidi_wrapper.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _scidi_wrapper.IntVector___nonzero__(self)
    def __bool__(self): return _scidi_wrapper.IntVector___bool__(self)
    def __len__(self): return _scidi_wrapper.IntVector___len__(self)
    def pop(self): return _scidi_wrapper.IntVector_pop(self)
    def __getslice__(self, *args): return _scidi_wrapper.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _scidi_wrapper.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _scidi_wrapper.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _scidi_wrapper.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _scidi_wrapper.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _scidi_wrapper.IntVector___setitem__(self, *args)
    def append(self, *args): return _scidi_wrapper.IntVector_append(self, *args)
    def empty(self): return _scidi_wrapper.IntVector_empty(self)
    def size(self): return _scidi_wrapper.IntVector_size(self)
    def clear(self): return _scidi_wrapper.IntVector_clear(self)
    def swap(self, *args): return _scidi_wrapper.IntVector_swap(self, *args)
    def get_allocator(self): return _scidi_wrapper.IntVector_get_allocator(self)
    def begin(self): return _scidi_wrapper.IntVector_begin(self)
    def end(self): return _scidi_wrapper.IntVector_end(self)
    def rbegin(self): return _scidi_wrapper.IntVector_rbegin(self)
    def rend(self): return _scidi_wrapper.IntVector_rend(self)
    def pop_back(self): return _scidi_wrapper.IntVector_pop_back(self)
    def erase(self, *args): return _scidi_wrapper.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _scidi_wrapper.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _scidi_wrapper.IntVector_push_back(self, *args)
    def front(self): return _scidi_wrapper.IntVector_front(self)
    def back(self): return _scidi_wrapper.IntVector_back(self)
    def assign(self, *args): return _scidi_wrapper.IntVector_assign(self, *args)
    def resize(self, *args): return _scidi_wrapper.IntVector_resize(self, *args)
    def insert(self, *args): return _scidi_wrapper.IntVector_insert(self, *args)
    def reserve(self, *args): return _scidi_wrapper.IntVector_reserve(self, *args)
    def capacity(self): return _scidi_wrapper.IntVector_capacity(self)
    __swig_destroy__ = _scidi_wrapper.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _scidi_wrapper.IntVector_swigregister
IntVector_swigregister(IntVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _scidi_wrapper.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _scidi_wrapper.StringVector___nonzero__(self)
    def __bool__(self): return _scidi_wrapper.StringVector___bool__(self)
    def __len__(self): return _scidi_wrapper.StringVector___len__(self)
    def pop(self): return _scidi_wrapper.StringVector_pop(self)
    def __getslice__(self, *args): return _scidi_wrapper.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _scidi_wrapper.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _scidi_wrapper.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _scidi_wrapper.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _scidi_wrapper.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _scidi_wrapper.StringVector___setitem__(self, *args)
    def append(self, *args): return _scidi_wrapper.StringVector_append(self, *args)
    def empty(self): return _scidi_wrapper.StringVector_empty(self)
    def size(self): return _scidi_wrapper.StringVector_size(self)
    def clear(self): return _scidi_wrapper.StringVector_clear(self)
    def swap(self, *args): return _scidi_wrapper.StringVector_swap(self, *args)
    def get_allocator(self): return _scidi_wrapper.StringVector_get_allocator(self)
    def begin(self): return _scidi_wrapper.StringVector_begin(self)
    def end(self): return _scidi_wrapper.StringVector_end(self)
    def rbegin(self): return _scidi_wrapper.StringVector_rbegin(self)
    def rend(self): return _scidi_wrapper.StringVector_rend(self)
    def pop_back(self): return _scidi_wrapper.StringVector_pop_back(self)
    def erase(self, *args): return _scidi_wrapper.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _scidi_wrapper.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _scidi_wrapper.StringVector_push_back(self, *args)
    def front(self): return _scidi_wrapper.StringVector_front(self)
    def back(self): return _scidi_wrapper.StringVector_back(self)
    def assign(self, *args): return _scidi_wrapper.StringVector_assign(self, *args)
    def resize(self, *args): return _scidi_wrapper.StringVector_resize(self, *args)
    def insert(self, *args): return _scidi_wrapper.StringVector_insert(self, *args)
    def reserve(self, *args): return _scidi_wrapper.StringVector_reserve(self, *args)
    def capacity(self): return _scidi_wrapper.StringVector_capacity(self)
    __swig_destroy__ = _scidi_wrapper.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _scidi_wrapper.StringVector_swigregister
StringVector_swigregister(StringVector)

class StringStringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringStringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringStringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _scidi_wrapper.StringStringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _scidi_wrapper.StringStringVector___nonzero__(self)
    def __bool__(self): return _scidi_wrapper.StringStringVector___bool__(self)
    def __len__(self): return _scidi_wrapper.StringStringVector___len__(self)
    def pop(self): return _scidi_wrapper.StringStringVector_pop(self)
    def __getslice__(self, *args): return _scidi_wrapper.StringStringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _scidi_wrapper.StringStringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _scidi_wrapper.StringStringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _scidi_wrapper.StringStringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _scidi_wrapper.StringStringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _scidi_wrapper.StringStringVector___setitem__(self, *args)
    def append(self, *args): return _scidi_wrapper.StringStringVector_append(self, *args)
    def empty(self): return _scidi_wrapper.StringStringVector_empty(self)
    def size(self): return _scidi_wrapper.StringStringVector_size(self)
    def clear(self): return _scidi_wrapper.StringStringVector_clear(self)
    def swap(self, *args): return _scidi_wrapper.StringStringVector_swap(self, *args)
    def get_allocator(self): return _scidi_wrapper.StringStringVector_get_allocator(self)
    def begin(self): return _scidi_wrapper.StringStringVector_begin(self)
    def end(self): return _scidi_wrapper.StringStringVector_end(self)
    def rbegin(self): return _scidi_wrapper.StringStringVector_rbegin(self)
    def rend(self): return _scidi_wrapper.StringStringVector_rend(self)
    def pop_back(self): return _scidi_wrapper.StringStringVector_pop_back(self)
    def erase(self, *args): return _scidi_wrapper.StringStringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _scidi_wrapper.new_StringStringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _scidi_wrapper.StringStringVector_push_back(self, *args)
    def front(self): return _scidi_wrapper.StringStringVector_front(self)
    def back(self): return _scidi_wrapper.StringStringVector_back(self)
    def assign(self, *args): return _scidi_wrapper.StringStringVector_assign(self, *args)
    def resize(self, *args): return _scidi_wrapper.StringStringVector_resize(self, *args)
    def insert(self, *args): return _scidi_wrapper.StringStringVector_insert(self, *args)
    def reserve(self, *args): return _scidi_wrapper.StringStringVector_reserve(self, *args)
    def capacity(self): return _scidi_wrapper.StringStringVector_capacity(self)
    __swig_destroy__ = _scidi_wrapper.delete_StringStringVector
    __del__ = lambda self : None;
StringStringVector_swigregister = _scidi_wrapper.StringStringVector_swigregister
StringStringVector_swigregister(StringStringVector)

class ScidiWrapper(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ScidiWrapper, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ScidiWrapper, name)
    __repr__ = _swig_repr
    def setData(self, *args): return _scidi_wrapper.ScidiWrapper_setData(self, *args)
    def getData(self): return _scidi_wrapper.ScidiWrapper_getData(self)
    def makeRules(self, *args): return _scidi_wrapper.ScidiWrapper_makeRules(self, *args)
    def getRules(self): return _scidi_wrapper.ScidiWrapper_getRules(self)
    def makeClasses(self): return _scidi_wrapper.ScidiWrapper_makeClasses(self)
    def getClasses(self): return _scidi_wrapper.ScidiWrapper_getClasses(self)
    def getIdealObjects(self): return _scidi_wrapper.ScidiWrapper_getIdealObjects(self)
    def getFisher(self): return _scidi_wrapper.ScidiWrapper_getFisher(self)
    def getYule(self): return _scidi_wrapper.ScidiWrapper_getYule(self)
    def __init__(self): 
        this = _scidi_wrapper.new_ScidiWrapper()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scidi_wrapper.delete_ScidiWrapper
    __del__ = lambda self : None;
ScidiWrapper_swigregister = _scidi_wrapper.ScidiWrapper_swigregister
ScidiWrapper_swigregister(ScidiWrapper)

# This file is compatible with both classic and new-style classes.


