Import('env')

env.ParseConfig('wx-config --cxxflags --libs') #wxXml
env.Append(CCFLAGS = ['-pthread'])
env.Append(CPPDEFINES=['SCIDI_DLL', 'SCIDI_DLL_EXPORTS', '__INCPP', 'savealign'])

sources = Glob('*.cpp')
sources.extend(Glob('./manager/*.cpp'))

env.SharedLibrary('scidi', sources, LIBS = env['LIBS'] + ['boost_regex', 'pthread'])
